- configs/egov-persister/tradelicense.yml
- configs/pdf-service/data-config/tl-certificate.json
- configs/pdf-service/data-config/tl-receipt.json
- configs/pdf-service/data-config/tlapplication-dhobi.json
- configs/pdf-service/data-config/tlapplication-driving.json
- configs/pdf-service/data-config/tlapplication-oldBook.json
- configs/pdf-service/data-config/tlapplication-rehri.json
- configs/pdf-service/format-config/tl-certificate.json
- configs/pdf-service/format-config/tl-receipt.json
- configs/pdf-service/format-config/tlapplication-dhobi.json
- configs/pdf-service/format-config/tlapplication-driving.json
- configs/pdf-service/format-config/tlapplication-oldBook.json
- configs/pdf-service/format-config/tlapplication-rehri.json
Fix the bugs.
Modify the config, spacing and structure accordingly for UAT.
> Updated pdf configs.

- configs/reports/configs/tl-reports.yml
Change trade license application status report.
> Change query for trade license status report.

- configs/egov-localization/W&S_Localization
> W&S Localization

- configs/egov-localization/w&s-localization-28210121-1
> w&s-localization-28210121-1

- configs/egov-localization/w&s-localization-28210121-2
> w&s-localization-28210121-2

- configs/egov-localization/w&s-localization-28210121-5
> w&s-localization-28210121-5

- configs/pdf-service/data-config/payslip.json
- configs/pdf-service/format-config/payslip.json
Integration service -payslip pdf
> Integration service -payslip pdf

- configs/pdf-service/data-config/payslip.json
- configs/pdf-service/format-config/payslip.json
Integration Service-dynamic payload changes in payslip file
> Integration Service-dynamic payload changes in payslip file

- configs/egov-localization/localization-integration_04_02_2020-2
localization-integration_04_02_2020-2
> localization-integration_04_02_2020-2

- configs/egov-localization/Localisation-common
localization for create in common module
> localization for create in common module

- configs/egov-localization/rainmaker-common-dashboard.sql
1. Dashboard localization added for HC, Aport and Culture, PGR, and Echallan
2. Localization added for workflow preview
> Dashboard Localization added

- configs/egov-localization/rainmaker-dashboard.sql
Labels updated for dashboard module
> Dashboard labels update

- configs/egov-localization/rainmaker-dashboard.sql
Localization card header added.
> Localizaton labbls added

- configs/pdf-service/data-config/payslip.json
- configs/pdf-service/format-config/payslip.json
Payslip pdf format modification
> Payslip pdf format modification

- configs/egov-persister/integration-services-persister.yml
Integration service eoffice topics added
> Integration service eoffice topics added

- configs/egov-persister/bookings-persister.yml
> room persister changes

- configs/egov-persister/bookings-persister.yml
> searching related

- configs/egov-persister/bookings-persister.yml
> nominee name added

- configs/egov-localization/rainmaker-dashboard.sql
Labels added for card name in Work and WNS dashboard
> Localization labels added

- configs/egov-localization/rainmaker-dashboard.sql
> Localization Dashboard

- configs/reports/configs/pgr-reports.yml
PGR description report filter changes
> PGR description report filter changes

- configs/pdf-service/data-config/advertisement-noc.json
- configs/pdf-service/data-config/advertisement-receipt.json
- configs/pdf-service/data-config/pet-noc.json
- configs/pdf-service/data-config/pet-receipt.json
- configs/pdf-service/data-config/roadcut-receipt.json
- configs/pdf-service/data-config/sellmeat-noc.json
- configs/pdf-service/format-config/advertisement-noc.json
- configs/pdf-service/format-config/advertisement-receipt.json
- configs/pdf-service/format-config/pet-noc.json
- configs/pdf-service/format-config/pet-receipt.json
- configs/pdf-service/format-config/roadcut-receipt.json
- configs/pdf-service/format-config/sellmeat-noc.json
- configs/reports/configs/pgr-reports.yml
Resolved issues of OPMS receipt and certificate
> Resolved issues of OPMS receipt and certificate

- configs/reports/configs/pgr-reports.yml
> PGR Complaint report added

- configs/reports/configs/hc-reports.yml
> HCreport issue fixes

- configs/pdf-service/data-config/challanReceipt-ec.json
- configs/pdf-service/format-config/challanReceipt-ec.json
> Echallan Receipt changes

- configs/pdf-service/data-config/nulm-certificate-susv.json
- configs/pdf-service/format-config/nulm-certificate-susv.json
> NULM issue fixed

- configs/pdf-service/data-config/nulm-certificate-smid.json
- configs/pdf-service/data-config/nulm-certificate-suh.json
- configs/pdf-service/data-config/nulm-certificate-susv.json
- configs/pdf-service/data-config/nulm-certificate-susvUpdate.json
- configs/pdf-service/format-config/nulm-certificate-smid.json
- configs/pdf-service/format-config/nulm-certificate-suh.json
- configs/pdf-service/format-config/nulm-certificate-susv.json
> NULM issue fixes

- configs/pdf-service/data-config/challanReceipt-ec.json
- configs/pdf-service/data-config/challanReceiptVehicle-ec.json
- configs/pdf-service/data-config/hcServiceRequest.json
- configs/pdf-service/data-config/nulm-certificate-sep.json
- configs/pdf-service/data-config/nulm-certificate-smid.json
- configs/pdf-service/data-config/nulm-certificate-suh.json
- configs/pdf-service/data-config/nulm-certificate-susv.json
- configs/pdf-service/data-config/nulm-certificate-susvUpdate.json
- configs/pdf-service/data-config/store-asset-indent-inward.json
- configs/pdf-service/data-config/store-asset-indent-issue-note.json
- configs/pdf-service/data-config/store-asset-indent-note.json
- configs/pdf-service/data-config/store-asset-indent-outward.json
- configs/pdf-service/data-config/store-asset-indent-transfer.json
- configs/pdf-service/data-config/store-asset-misc-material-note.json
- configs/pdf-service/data-config/store-asset-mrn-receipt.json
- configs/pdf-service/data-config/store-asset-non-indent-issue-note.json
- configs/pdf-service/data-config/store-asset-purchase-order.json
- configs/pdf-service/data-config/store-asset-report-closing-balance.json
- configs/pdf-service/data-config/store-asset-report-inventory-register.json
- configs/pdf-service/data-config/store-asset-report-opening-balance.json
- configs/pdf-service/data-config/store-asset-stock-report.json
- configs/pdf-service/data-config/tl-certificate.json
- configs/pdf-service/data-config/tl-receipt.json
- configs/pdf-service/data-config/tlapplication-dhobi.json
- configs/pdf-service/data-config/tlapplication-driving.json
- configs/pdf-service/data-config/tlapplication-oldBook.json
- configs/pdf-service/data-config/tlapplication-rehri.json
- configs/pdf-service/data-config/tlapplication.json
> Logo url path changes

- configs/pdf-service/format-config/sellMeat-receipt.json
> Sell Meat Receipt changes

- configs/egov-localization/rainmaker-dashboard.sql
'WNS_dashboard_1' => 'Water Dashboard'
> Update dashboard localization

- configs/egov-persister/nulm-persister.yml
> NULM alf topic added

- configs/egov-persister/nulm-persister.yml
> nulm update alf topic added

- configs/reports/configs/pgr-reports.yml
PGR Description Report added columns
> PGR Description Report added columns

- configs/egov-localization/rainmaker-pm-services.sql
These keys are added 
'SELLMEAT.ID_PROOF'
'PET-NOC_NEW_APPLICATION'
'SELL-MEAT-NOC_NEW_APPLICATION'
'ADVERTISEMENT-NOC_NEW_APPLICATION',
'ROADCUT-NOC_NEW_APPLICATION'
'NOC_HOME_SEARCH_RESULTS_NEW_APP_BUTTON'
These key is updated
SELLMEATNOC_FEE
> OPMS Localization for Sell meat

- configs/egov-persister/nulm-persister.yml
> Nulm alf topic changes

- configs/egov-localization/rainmaker-nulm-localization.sql
- configs/egov-localization/rainmaker-pm-services.sql
OPMS and NULM lables update and addded
> Labels added

- configs/egov-persister/nulm-persister.yml
> NULM susv changes

- configs/egov-persister/nulm-persister.yml
> topic name changes

- configs/egov-localization/rainmaker-pm-services.sql
NOC_PAYMENT_COLLECTION_SUCCESS_MESSAGE_MAIN
NOC_CONFIRMATION_BUTTON_DOWNLOAD_RECEIPT
NOC_PMT_RCPT_NO
These three above kesy need to check in 
Inser message or Insert public.message query
> Sellmeat mobile no field key added

- configs/egov-localization/rainmaker-common-pm-services.sql
- configs/egov-localization/rainmaker-nulm-localization.sql
> OPMS NULM label change 
